# Generated by Django 5.1.1 on 2024-10-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_tasklist_taskcreate_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreate',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
