# Generated by Django 5.1.1 on 2024-10-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_taskcreate_is_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcreate',
            name='priority',
        ),
    ]
